name: Create Staging Environment on Render

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true

jobs:
  deploy:
    name: 'Deploy to Staging on Render'
    runs-on: ubuntu-latest

    env:
      RENDER_CLIENT_SERVICE_ID: ${{ secrets.RENDER_CLIENT_SERVICE_ID }}
      RENDER_SERVER_SERVICE_ID: ${{ secrets.RENDER_SERVER_SERVICE_ID }}
      RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.inputs.PR_number }}/merge

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: 'Install Dependencies'
        run: |
          cd ./client
          npm install
          cd ../server
          npm install

      - name: 'Build Frontend'
        run: |
          cd ./client
          npm run build

      - name: 'Deploy Frontend to Render on https://primemarket-client-bubt.onrender.com/'
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ env.RENDER_CLIENT_SERVICE_ID }}
          api-key: ${{ env.RENDER_API_TOKEN }}

      - name: 'Deploy Backend to Render'
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ env.RENDER_SERVER_SERVICE_ID }}
          api-key: ${{ env.RENDER_API_TOKEN }}

      - name: 'Setup tmate session'
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
